openapi: '3.0.0'
info:
  title: Common
  version: '1.0'

paths:

components:
  schemas:
    GeneralErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
        traceId:
          type: string

  parameters:
    Offset:
      in: query
      name: offset
      schema:
        default: 0
        minimum: 0
        type: integer
      required: true

    Limit:
      in: query
      name: limit
      schema:
        default: 10
        maximum: 100
        type: integer
      required: true

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralErrorResponse'
    Conflicts:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralErrorResponse'
    UnproccessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralErrorResponse'
